@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7InJvb3QiOnRydWUsIl9pZCI6IjVmY2M0YmJlYTVmMTZmMmZmY2IwNGFlZiIsIm5vbWUiOiJLZWxzZW4gQnJpdG8iLCJlbWFpbCI6ImtlbHNlbi5icml0b0BnbWFpbC5jb20iLCJzZW5oYSI6IiQyYSQwOCRFU3F6ZkVLbDNsM0xnaTBEbFBFQnBlRERySmZJZ2pLaHV3UVBjSjR0bDQ0WnhuZUtZMHZ3eSIsIl9fdiI6MH0sImlhdCI6MTYwNzI5NDM2MCwiZXhwIjoxNjA3Mjk3OTYwfQ.4GCsM8Ej4kGWedfEMAS_b9-doEMR2IRo18igBXmcpfw
@idUsuario = 5fcc4bb7a5f16f2ffcb04aee

### index usuario
GET {{baseUrl}}/usuario/session
Authorization: Bearer {{token}}

### index usuario
GET {{baseUrl}}/usuario
Authorization: Bearer {{token}}


### show usuario
GET {{baseUrl}}/usuario/{{idUsuario}}
Authorization: Bearer {{token}}


### delete usuario
DELETE {{baseUrl}}/usuario/{{idUsuario}}
Authorization: Bearer {{token}}


### criar usuário
POST {{baseUrl}}/usuario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Tati Veil",
    "email": "tativeil@gmail.com",
    "senha": "123456"
}


### alterar usuário
PUT {{baseUrl}}/usuario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "_id": "5fcc4bb7a5f16f2ffcb04aee",
    "nome": "Tati Veil",
    "email": "tativeil@gmail.com",
    "senha": "123456",
    "root": false
}


### authenticate
POST {{baseUrl}}/usuario/login
Content-Type: application/json

{
    "email": "giovanna.brito@gmail.com",
    "senha": "123456"
}


