@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmNjNGJiZWE1ZjE2ZjJmZmNiMDRhZWYiLCJpYXQiOjE2MDcyMjczMjQsImV4cCI6MTYwNzIzMDkyNH0.xXezDyLnkLOVuyhQLMOYK6xaJR-I4yNrzmEpsKxfYL8
@idUsuario = 5fcc51f6de5c52288c46bb3d

### lista usuario
GET {{baseUrl}}/usuario
Authorization: Bearer {{token}}


### get usuario
GET {{baseUrl}}/usuario/{{idUsuario}}
Authorization: Bearer {{token}}


### destroy usuario
DELETE {{baseUrl}}/usuario/{{idUsuario}}
Authorization: Bearer {{token}}


### criar usuário
POST {{baseUrl}}/usuario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Tati Veil",
    "email": "tativeillllll@gmail.com",
    "senha": "123456"
}


### alterar usuário
PUT {{baseUrl}}/usuario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "_id": "5fcc4bb7a5f16f2ffcb04aee",
    "nome": "Fátima Brito",
    "email": "fatima.brito@gmail.com",
    "senha": "123456"
}


### authenticate
POST {{baseUrl}}/usuario/authenticate
Content-Type: application/json

{
    "email": "kelsen.brito@gmail.com",
    "senha": "123456"
}


