@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM4NmM1MmE2NWU3YTQ3OWNiYWIzMzUiLCJpYXQiOjE2MDY5NzA0ODQsImV4cCI6MTYwNzA1Njg4NH0.ZANisozu1Ajm95cOPLKrdHgbfDl26k4EkmyEtiW5F1U

### lista usuario
GET {{baseUrl}}/usuario
Authorization: Bearer {{token}}


### get usuario
GET {{baseUrl}}/usuario/5fc5c709e03ae13740f6f6a7
Authorization: Bearer {{token}}


### destroy usuario
DELETE {{baseUrl}}/usuario/5fc6ddd9fbe711430cecf804
Authorization: Bearer {{token}}


### criar usuário
POST {{baseUrl}}/usuario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Geraldo Brito",
    "email": "geraldo.brito@gmail.com",
    "senha": "123456"
}


### alterar usuário
POST {{baseUrl}}/usuario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "_id": "5fc9320de5f50c0aac46b18a",
    "nome": "Tati Veil",
    "email": "tativeil@gmail.com",
    "senha": "123456"
}


### authenticate
POST {{baseUrl}}/usuario/authenticate
Content-Type: application/json

{
    "email": "geraldo.brito@gmail.com",
    "senha": "123456"
}


